# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Richard Hartigan
description: "Hi I'm Richard. For the past 15 years I've worked in Digital Media, advising some of the worlds largest brands how to mix technology, creativity and innovation to maximise their return on investment.  I am passionate about translating data into insights that can drive meaningful busines action. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.richardhartigan.com" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "London, UK"
resume_url: https://www.richardhartigan.com/p/about-me.html
avatar_image: /img/RAH.jpeg

#-------------------------------
# Contact links
linkedln: "https://linkedln.com/richardhartigan" # Add your linkedln handle
github: "https://github.com/richardhartigan"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

